var searchData=
[
  ['of_20second_20value_0',['RTCEx Substract Fraction Of Second Value',['../group___r_t_c_ex___substract___fraction___of___second___value.html',1,'']]],
  ['of_20stop_20bits_1',['of Stop Bits',['../group___s_m_a_r_t_c_a_r_d___stop___bits.html',1,'SMARTCARD Number of Stop Bits'],['../group___u_a_r_t___stop___bits.html',1,'UART Number of Stop Bits'],['../group___u_s_a_r_t___stop___bits.html',1,'USART Number of Stop Bits']]],
  ['of_20view_2',['I2C Transfer Direction Master Point of View',['../group___i2_c___x_f_e_r_d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['offsets_3',['Register offsets',['../group___r_c_c___register___offset.html',1,'']]],
  ['on_20gpio_4',['Fast Mode Plus on GPIO',['../group___s_y_s_c_f_g___fast_mode_plus___g_p_i_o.html',1,'']]],
  ['on_20rx_20error_5',['UART Advanced Feature DMA Disable On Rx Error',['../group___u_a_r_t___d_m_a___disable__on___rx___error.html',1,'']]],
  ['on_20rx_20error_6',['SMARTCARD advanced feature DMA Disable on Rx Error',['../group___s_m_a_r_t_c_a_r_d___d_m_a___disable__on___rx___error.html',1,'']]],
  ['one_20bit_20sampling_7',['IRDA One Bit Sampling',['../group___i_r_d_a___one___bit.html',1,'']]],
  ['one_20bit_20sampling_20method_8',['One Bit Sampling Method',['../group___s_m_a_r_t_c_a_r_d___one_bit___sampling.html',1,'SMARTCARD One Bit Sampling Method'],['../group___u_a_r_t___one_bit___sampling.html',1,'UART One Bit Sampling Method']]],
  ['one_20pulse_20functions_9',['TIM One Pulse functions',['../group___t_i_m___exported___functions___group5.html',1,'']]],
  ['one_20pulse_20mode_10',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_11',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_12',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operating_20mode_20definition_13',['Operating Mode Definition',['../group___i2_c___operating___mode___definition.html',1,'']]],
  ['operating_20mode_20definitions_14',['Timer Operating Mode Definitions',['../group___r_t_c___timer___operating___mode___definitions.html',1,'']]],
  ['operation_20definition_15',['Operation Definition',['../group___i2_c___operation___definition.html',1,'']]],
  ['operation_20functions_16',['operation functions',['../group___i2_c___exported___functions___group2.html',1,'Input and Output operation functions'],['../group___s_m_b_u_s___exported___functions___group2.html',1,'Input and Output operation functions'],['../group___d_a_c___exported___functions___group2.html',1,'IO operation functions'],['../group___g_p_i_o___exported___functions___group2.html',1,'IO operation functions'],['../group___i_w_d_g___exported___functions___group2.html',1,'IO operation functions'],['../group___i_r_d_a___exported___functions___group2.html',1,'IO operation functions'],['../group___u_a_r_t___exported___functions___group2.html',1,'IO operation functions'],['../group___u_s_a_r_t___exported___functions___group2.html',1,'IO operation functions']]],
  ['option_17',['IWDG Window option',['../group___i_w_d_g___window__option.html',1,'']]],
  ['option_20bytes_20boot_20bit1_20setup_18',['FLASH Option Bytes BOOT Bit1 Setup',['../group___f_l_a_s_h_ex___option___bytes___b_o_o_t_bit1.html',1,'']]],
  ['option_20bytes_20bor_20level_19',['FLASHEx Option Bytes BOR Level',['../group___f_l_a_s_h_ex___option___bytes___b_o_r___level.html',1,'']]],
  ['option_20bytes_20iwatchdog_20',['FLASHEx Option Bytes IWatchdog',['../group___f_l_a_s_h_ex___option___bytes___i_watchdog.html',1,'']]],
  ['option_20bytes_20nrst_5fstdby_21',['FLASHEx Option Bytes nRST_STDBY',['../group___f_l_a_s_h_ex___option___bytes__n_r_s_t___s_t_d_b_y.html',1,'']]],
  ['option_20bytes_20nrst_5fstop_22',['FLASHEx Option Bytes nRST_STOP',['../group___f_l_a_s_h_ex___option___bytes__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20bytes_20read_20protection_23',['FLASHEx Option Bytes Read Protection',['../group___f_l_a_s_h_ex___option___bytes___read___protection.html',1,'']]],
  ['option_20bytes_20write_20protection1_24',['FLASHEx Option Bytes Write Protection1',['../group___f_l_a_s_h_ex___option___bytes___write___protection1.html',1,'']]],
  ['option_20type_25',['FLASHEx Option Type',['../group___f_l_a_s_h_ex___option___type.html',1,'']]],
  ['options_26',['I2C Sequential Transfer Options',['../group___i2_c___x_f_e_r_o_p_t_i_o_n_s.html',1,'']]],
  ['or_20disabled_20status_27',['or Disabled Status',['../group___r_c_c___a_h_b___peripheral___clock___enable___disable___status.html',1,'AHB Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b___clock___sleep___enable___disable___status.html',1,'AHB Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___i_o_p_o_r_t___peripheral___clock___enable___disable___status.html',1,'IOPORT Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___i_o_p_o_r_t___clock___sleep___enable___disable___status.html',1,'IOPORT Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['or_20not_20default_20init_20value_20is_20used_28',['Indicates whether or not default init value is used',['../group___c_r_c___default___init_value___use.html',1,'']]],
  ['or_20not_20default_20polynomial_20is_20used_29',['Indicates whether or not default polynomial is used',['../group___c_r_c___default___polynomial.html',1,'']]],
  ['or_20stop_20mode_30',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['oscillator_20type_31',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['out_32',['RTC Output Type ALARM OUT',['../group___r_t_c___output___type___a_l_a_r_m___o_u_t.html',1,'']]],
  ['out_20remap_33',['RTC Output ALARM OUT Remap',['../group___r_t_c___output___a_l_a_r_m___o_u_t___remap.html',1,'']]],
  ['out_20selection_34',['SYSCFG VREFINT Out Selection',['../group___s_y_s_c_f_g___v_r_e_f_i_n_t___o_u_t___s_e_l_e_c_t.html',1,'']]],
  ['out_20value_35',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['output_36',['COMP Output',['../group___c_o_m_p___output.html',1,'']]],
  ['output_20alarm_20out_20remap_37',['RTC Output ALARM OUT Remap',['../group___r_t_c___output___a_l_a_r_m___o_u_t___remap.html',1,'']]],
  ['output_20buffer_38',['DAC output buffer',['../group___d_a_c__output__buffer.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_39',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_40',['TIM Output Compare functions',['../group___t_i_m___exported___functions___group2.html',1,'']]],
  ['output_20compare_20polarity_41',['TIM Output Compare Polarity',['../group___t_i_m___output___compare___polarity.html',1,'']]],
  ['output_20compare_20state_42',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20data_20inversion_20modes_43',['Output Data Inversion Modes',['../group___c_r_c_ex___output___data___inversion.html',1,'']]],
  ['output_20fast_20state_44',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['output_20level_45',['COMP Output Level',['../group___c_o_m_p___output_level.html',1,'']]],
  ['output_20operation_20functions_46',['Output operation functions',['../group___i2_c___exported___functions___group2.html',1,'Input and Output operation functions'],['../group___s_m_b_u_s___exported___functions___group2.html',1,'Input and Output operation functions']]],
  ['output_20polarity_47',['COMP output Polarity',['../group___c_o_m_p___output_polarity.html',1,'']]],
  ['output_20polarity_20definitions_48',['RTC Output Polarity Definitions',['../group___r_t_c___output___polarity___definitions.html',1,'']]],
  ['output_20selection_20definition_49',['Output Selection Definition',['../group___r_t_c_ex___output__selection___definitions.html',1,'RTCEx Output Selection Definition'],['../group___r_t_c_ex___output__selection___definition.html',1,'RTCEx Output Selection Definition']]],
  ['output_20selection_20definitions_50',['Calib Output Selection Definitions',['../group___r_t_c_ex___calib___output___selection___definitions.html',1,'']]],
  ['output_20selection_20definitions_51',['RTCEx Calib Output selection Definitions',['../group___r_t_c_ex___calib___output__selection___definitions.html',1,'']]],
  ['output_20to_20exti_52',['COMP output to EXTI',['../group___c_o_m_p___e_x_t_i___trigger_mode.html',1,'']]],
  ['output_20type_20alarm_20out_53',['RTC Output Type ALARM OUT',['../group___r_t_c___output___type___a_l_a_r_m___o_u_t.html',1,'']]],
  ['over_20sampling_54',['Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'UART Over Sampling'],['../group___u_s_a_r_t___over___sampling.html',1,'USART Over Sampling']]],
  ['overrun_55',['ADC Overrun',['../group___a_d_c___overrun.html',1,'']]],
  ['overrun_20disable_56',['Overrun Disable',['../group___s_m_a_r_t_c_a_r_d___overrun___disable.html',1,'SMARTCARD advanced feature Overrun Disable'],['../group___u_a_r_t___overrun___disable.html',1,'UART Advanced Feature Overrun Disable']]],
  ['oversampling_20mode_57',['ADC Triggered Oversampling Mode',['../group___a_d_c___triggered___oversampling___mode.html',1,'']]],
  ['oversampling_20ratio_58',['ADC Oversampling Ratio',['../group___a_d_c___oversampling___ratio.html',1,'']]],
  ['own_20address_59',['Own address',['../group___i2_c___own___address.html',1,'']]],
  ['own_20address2_20masks_60',['I2C Own Address2 Masks',['../group___i2_c___o_w_n___a_d_d_r_e_s_s2___m_a_s_k_s.html',1,'']]],
  ['ownaddress2_20masks_61',['SMBUS ownaddress2 masks',['../group___s_m_b_u_s__own__address2__masks.html',1,'']]]
];
